// Generated by dart2js (full emitter, strong), the Dart to JavaScript compiler version: 2.1.0.
self.$dart_deferred_initializers$ = self.$dart_deferred_initializers$ || Object.create(null);
$dart_deferred_initializers$.current = function($globals$, $) {
  // /* ::norenaming::
  var A = $globals$.A;
  var B = $globals$.B;
  var C = $globals$.C;
  var D = $globals$.D;
  var E = $globals$.E;
  var F = $globals$.F;
  var G = $globals$.G;
  var H = $globals$.H;
  var J = $globals$.J;
  var K = $globals$.K;
  var L = $globals$.L;
  var M = $globals$.M;
  var N = $globals$.N;
  var O = $globals$.O;
  var P = $globals$.P;
  var Q = $globals$.Q;
  var R = $globals$.R;
  var S = $globals$.S;
  var T = $globals$.T;
  var U = $globals$.U;
  var V = $globals$.V;
  var W = $globals$.W;
  var X = $globals$.X;
  var Y = $globals$.Y;
  var Z = $globals$.Z;
  var init = $globals$.init;
  var setupProgram = $globals$.setupProgram;
  var Isolate = $globals$.Isolate;
  var dart = [["dart2js._js_primitives", "dart:_js_primitives",, H, {
    "^": "",
    printString: function(string) {
      if (typeof dartPrint == "function") {
        dartPrint(string);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(string);
        return;
      }
      if (typeof window == "object")
        return;
      if (typeof print == "function") {
        print(string);
        return;
      }
      throw "Unable to print message: " + String(string);
    }
  }], ["", "p.dart",, R, {
    "^": "",
    hello: function() {
      H.printString("hello");
    }
  }]];
  setupProgram(dart, init.metadata.length, init.types.length);
  var deferredMetadata = [];
  var deferredTypes = [];
  init.metadata.push.apply(init.metadata, deferredMetadata);
  init.types.push.apply(init.types, deferredTypes);
  // No constants in program.
  // No lazy statics.
};
;
$dart_deferred_initializers$["G0dMMcX8PTQ9xaz7VDXsk0l9ZmY="] = $dart_deferred_initializers$.current;

//# sourceMappingURL=p.js_1.part.js.map
