name: an3
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alexey Zolotykh <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  js: any

dev_dependencies:
  test: ^1.0.0
